LogPath: logs
Mysql:
  -
    Host: 127.0.0.1
    Port: 3306
    User: root
    Password: 123456789
    Database: database1
    Name: source
  -
    Host: 127.0.0.1
    Port: 3306
    User: root
    Password: 123456789
    Database: database2
    Name: target